---
title: "Viz_II"
output: github_document
date: "2025-09-30"
---

```{r}
library(tidyverse)
library(patchwork)
library(p8105.datasets)
```

Import the weather data
```{r}
data("weather_df")
```

Let's make our basic scatterplot
```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point(aes(color=name), alpha=0.5) +
  labs(
    x="Minimum daily temp", 
    y="Maximum daily temp",
    title="Temperature scatterplot",
    caption = "Data from NOAA",
    color="Location" #side legend
  )
```

##Scales
```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point(aes(color=name), alpha=0.5) +
  labs(
    x="Minimum daily temp", 
    y="Maximum daily temp",
    title="Temperature scatterplot",
    caption = "Data from NOAA",
    color="Location" #side legend
  ) +
  scale_x_continuous(
    breaks=c(-20,0,25),
    labels=c("-20C", "0", "25")
  ) +
  scale_y_continuous(
    trans="sqrt",
    limits=c(10, 30) #zoom in
  )
```

```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point(aes(color=name), alpha=0.5) +
  labs(
    x="Minimum daily temp", 
    y="Maximum daily temp",
    title="Temperature scatterplot",
    caption = "Data from NOAA",
    color="Location" #side legend
  ) +
  scale_x_continuous(
    breaks=c(-20,0,25),
    labels=c("-20C", "0", "25")
  ) +
  viridis::scale_color_viridis(
    discrete=TRUE
  )
```

